In [1]:
from bs4 import BeautifulSoup
import re
import requests
import pandas as pd
import os

In [2]:
"""
entry_urls = []

start_date = "2006-07-02"
end_date = "2006-07-05"
#base_url = "https://rip.ie/death-notice/s/all?page={}&start={}+00%3A00%3A00&end={}&sortField=a.createdAtCastToDate&sortDir=DESC&view=list"
p_count = 1

for p in range(1, p_count+1):
    base_url = "https://rip.ie/death-notice/s/all?page=" + str(p) + "&start=" + start_date + "+00%3A00%3A00&end=" + end_date + "&sortField=a.createdAtCastToDate&sortDir=DESC&view=list"
    #entry_urls.append(base_url.format(p, start_date, end_date))
    entry_urls.append(base_url)
"""

'\nentry_urls = []\n\nstart_date = "2006-07-02"\nend_date = "2006-07-05"\n#base_url = "https://rip.ie/death-notice/s/all?page={}&start={}+00%3A00%3A00&end={}&sortField=a.createdAtCastToDate&sortDir=DESC&view=list"\np_count = 1\n\nfor p in range(1, p_count+1):\n    base_url = "https://rip.ie/death-notice/s/all?page=" + str(p) + "&start=" + start_date + "+00%3A00%3A00&end=" + end_date + "&sortField=a.createdAtCastToDate&sortDir=DESC&view=list"\n    #entry_urls.append(base_url.format(p, start_date, end_date))\n    entry_urls.append(base_url)\n'

In [3]:
antrim_entry_urls = []

for p in range(1, 40):
    antrim_base_url = "https://rip.ie/death-notice/s/antrim?page=" + str(p) + "&start=2006-07-02+00%3A00%3A00&end=today&sortField=a.createdAtCastToDate&sortDir=DESC&view=list"
    antrim_entry_urls.append(antrim_base_url)

In [4]:
def re_url(url):
    try:
        response = requests.get(url)
        if response.status_code == 200:
            return response.text
        else:
            print(f"Failed to retrieve data from {url}. Status code: {response.status_code}")
            return None
    except Exception as e:
        print(f"Error while processing {url}: {str(e)}")
        return None

In [5]:
def scrape_html(html):
    soup = BeautifulSoup(html, 'html.parser')
    return soup

In [6]:
def get_ID(url):
    url_pattern = r'https://rip.ie/death-notice/([^/]+)-([^/]+)-([^/]+)(?:-([^/]+))?-(\d+)'
    m = re.match(url_pattern, url)
    if m:
        return m.group(5)  
    else:
        print("Pattern did not match.")

In [7]:
def get_url(soup):
    url_list = []
    anchors = soup.find_all('a', class_='showdown-dn-link')
    urls = [anchor['href'] for anchor in anchors]
    for url in urls:
        url_list.append("https://rip.ie" + url)
    return url_list

In [8]:
def get_name(soup):
    name_val = soup.find('h1', class_='DeathNotice_person-name__lkvex')
    if name_val:
        name = name_val.get_text()
        name = name.strip()
        name = name.replace("Â", "")
        name = name.replace("nee", "née")
        name = name.replace("nÃ©e", "née")
        name = name.replace("\n", " ")
        name = name.replace("â", "’")
        return name
    else:
        return None

In [9]:
def get_loc(soup):
    locations = {}
    loc_val = soup.find('div', class_='DeathNotice_tags-item__Fp1X4')
    if loc_val:
        raw_loc = loc_val.get_text()
        loc = [word.strip() for word in raw_loc.split(",") + raw_loc.split("/")]
        city_town = loc[-1]
        locations["City"] = city_town.split(",")[-1]
        locations["Town"] = city_town.split(",")[:-1]
        return locations
    else:
        return None

In [10]:
def get_dates(soup):
    date_list = {}

    published_date_value = soup.find('p', class_='DeathNotice_dates-published-date__M0A_i')
    if published_date_value:
        date_list["Published Date"] = published_date_value.get_text()
    else:
        date_list["Published Date"] = None

    death_date_value = soup.find('p', class_='DeathNotice_dates-death-date__bR7g_')
    if death_date_value:
        date_list["Death Date"] = death_date_value.get_text()
    else:
        date_list["Death Date"] = None

    return date_list

In [11]:
def get_obituary(soup):
    description = soup.find('div', class_='DeathNotice_description__sY_tC word-break')
    if description:
        text = description.get_text()
        text = text.strip()
        text = text.replace("Â", "")
        text = text.replace("nee", "née")
        text = text.replace("nÃ©e", "née")
        text = text.replace("\n", " ")
        text = text.replace("â", "’")
        text = text.replace("Å", "")
        text = text.replace("Ä", "")
        text = text.replace("", "")
        return text
    else:
        return None

In [12]:
def get_page_data(entry_urls):
    data_list = []

    for entry_url in entry_urls:
        page_data = re_url(entry_url)
        if page_data:
            url_list = get_url(scrape_html(page_data))
            
    for u in url_list:
        s = scrape_html(re_url(u))
        identity = get_ID(u)
        name = get_name(s)
        loc = get_loc(s)
        dates = get_dates(s)
        obituary_text = get_obituary(s)

        data_list.append({
            "Name": name,
            "ID": identity,
            "City": loc["City"],
            "Town": loc["Town"],
            "Published Date": dates["Published Date"],
            "Death Date": dates["Death Date"],
            "Obituary Text": obituary_text
    })

    df = pd.DataFrame(data_list)
    return df

In [13]:
rip_df = get_page_data(antrim_entry_urls)
rip_df

,Name,ID,City,Town,Published Date,Death Date,Obituary Text
0,Joyce LAWSON(née Poots),532921,Antrim,[Crumlin],Monday 16th October 2023,Saturday 14th October 2023,LAWSON (née Poots) Joyce (Late of Lucan and fo...
1,MERVILLE ASHTON,532919,Antrim,[Newtownabbey],Monday 16th October 2023,Saturday 14th October 2023,"Ashton, Merville. 14th October 2023, peacefull..."
2,James Browne,532892,Antrim,[Belfast],Monday 16th October 2023,Sunday 15th October 2023,"BROWNE, James, Noel, Innisfayle Park, Belfast...."
3,Jacinta O'Connor(née Reilly),532853,Antrim,[Belfast],Monday 16th October 2023,Saturday 14th October 2023,"O’Connor, (Coill Rua, Inverin, Co. Galway & fo..."
4,Colette Gilligan,532842,Antrim,[Belfast],Sunday 15th October 2023,Sunday 15th October 2023,"Gilligan, Colette passed away peacefully after..."
5,Catherine (Kathleen) MAGEE(née Hughes),532413,Antrim,[Belfast],Tuesday 10th October 2023,Monday 9th October 2023,"Magee (née Hughes), Cashel Road, Mantlehill, G..."
6,Brother Anthony McCrave C.Ss.R,532352,Dublin,[],Tuesday 10th October 2023,Tuesday 10th October 2023,"McCrave, Brother Anthony CSs.R. Clonard Monast..."
7,Marion Deane(née Treacy),532248,Antrim,[Belfast],Monday 9th October 2023,Monday 9th October 2023,"Teacher and scholar. Originally of Belfast, la..."
8,Sean (Fitzy) Fitzpatrick,532219,Antrim,"[Late of Ophir and Ashley Gardens Belfast), B...",Monday 9th October 2023,Sunday 8th October 2023,Fitzpatrick Sean (Fitzy) Passed away peacefull...
9,Terence (Terry) Monaghan,532194,Antrim,[Belfast],Monday 9th October 2023,Friday 6th October 2023,"Monaghan, Terence (Terry), (Glenview Park, Tal..."
10,Henry Ritchie,531978,Monaghan,[Newbliss],Saturday 7th October 2023,Friday 6th October 2023,"The death occurred of Henry Ritchie, Friday, 6..."
11,Mary Elliott(née McFall),531622,Kildare,[],Tuesday 3rd October 2023,Tuesday 3rd October 2023,Funeral Arrangements for the late Mary Elliott...
12,Michelle Kearney(née McPoland),531277,Antrim,[Lisburn],Saturday 30th September 2023,Thursday 28th September 2023,"KEARNEY, Michelle (née McPoland) â 28th Septe..."
13,Mary McKeown(née Donnelly),531220,Antrim,"[Skerry East Road, Ballymena]",Friday 29th September 2023,Thursday 28th September 2023,"Mc Keown, Mary (Newtowncrommelin, Ballymena) (..."
14,Jeremiah (Derry) Holyoake,530860,Kerry,[Listowel],Tuesday 26th September 2023,Sunday 24th September 2023,"Jeremiah (Derry) Holyoake, 24 Arran Street, Sp..."
15,Liam O'Mullan,530815,Antrim,[Cloughmills],Tuesday 26th September 2023,Monday 25th September 2023,"In loving memory of Liam O'Mullan (Rathuard, B..."

In [14]:
#output_directory = '/Users/idilbilgic/Desktop/STAGE4.1/COMP30170/suicide_rates_IE/output_monthly'
#rip_df.to_csv(os.path.join(output_directory, 'rip_output_antrim.csv'), index=False)

In [15]:
#rip_df.to_csv('rip_output_2006.csv', index=False)